blog:
  -
    link: http://dewieajaa.blogspot.co.id
    nama: Dewie Dean
    deskripsi: Ada kekuatan di balik kesederhanaan
  -
    link: http://www.henipuspita.net
    nama: Heni Puspita
    deskripsi: Catatan mama Rayyaan Razqa
  -
    link: http://japanesestation.com
    nama: Japanese Station
    deskripsi: Portal berita Jepang
  -
    link: http://www.mysatnite.com
    nama: My Satnite
    deskripsi: Your story is our story
  -
    link: http://teknokanz.blogspot.co.id
    nama: Si Kanz Technologies
    deskripsi: Teknologi, games, software, APK
  -
    link: http://syufiayaumma.blogspot.co.id
    nama: Syufia
    deskripsi: Life
  -
    link: http://muhammadzaini.com
    nama: Zen
    deskripsi: 'Senyumlah :)'